# Generated by Django 5.0.2 on 2024-03-08 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auditlog", "0015_alter_logentry_changes"),
    ]

    operations = [
        migrations.AddField(
            model_name="logentry",
            name="domain_object_id",
            field=models.BigIntegerField(
                blank=True, db_index=True, null=True, verbose_name="domain object id"
            ),
        ),
        migrations.AddField(
            model_name="logentry",
            name="path",
            field=models.CharField(
                blank=True,
                db_index=True,
                max_length=255,
                null=True,
                verbose_name="path",
            ),
        ),
    ]
