# Generated by Django 5.0.2 on 2024-03-12 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auditlog", "0017_logentry_is_approval"),
    ]

    operations = [
        migrations.AddField(
            model_name="logentry",
            name="code",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="code"
            ),
        ),
    ]
