# Generated by Django 5.0.3 on 2024-03-14 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auditlog", "0018_logentry_code"),
    ]

    operations = [
        migrations.AddField(
            model_name="logentry",
            name="approval_id",
            field=models.BigIntegerField(
                blank=True, null=True, verbose_name="approval id"
            ),
        ),
    ]
