# Generated by Django 5.0.3 on 2024-03-14 11:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("auditlog", "0019_logentry_approval_id"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="logentry",
            name="is_approval",
        ),
    ]
